name: CD — Test & Deploy    #name: is just the display name of the GitHub Actions workflow

on:
  push:
    branches: [main]    # only runs when code lands on main

jobs:

  # ── Job 1: Run tests ─────────────────────────────

  # CI part
  test:
    name: Run Tests
    runs-on: ubuntu-latest      #Kis machine pr ye run hoga
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm install
      - run: npm run test

  # ── Job 2: Deploy (only if tests passed) ─────────

  # CD part
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test              # ← waits for test job to succeed
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-da1s9hnqj5pc73d2mgp0?key=Rqdz9P9XBcU"
